[package]
name = "uniffi_meta"
version = "0.23.0"
edition = "2021"
description = "uniffi_meta"
homepage = "https://mozilla.github.io/uniffi-rs"
repository = "https://github.com/mozilla/uniffi-rs"
license = "MPL-2.0"
keywords = ["ffi", "bindgen"]

[dependencies]
anyhow = "1"
bytes = "1.3"
serde = { version = "1.0.136", features = ["derive"] }
siphasher = "0.3"
uniffi_checksum_derive = { version = "0.23.0", path = "../uniffi_checksum_derive" }
uniffi_core = { path = "../uniffi_core", version = "=0.23.0" }
